### ISSUE TITLE
[Feature Request] Longer lookback window than 1 but shorter than global

### ISSUE THREAD

**Issue by kanjieater** [Renji-XD/texthooker-ui#18]
One thing that I've seen happening using this texthooker-ui is that if you go back on a sub or something like that, you can get a lot of repetition in t-ui. I think the anacreon one I had used previously had a longer lookback window where it wouldn't add the line from, but also wasn't global. If a character repeats something a few hours later, you probably want to allow it in the texthooker. But if you go back a few subs or a character repeats something in the last 2 minutes, you probably don't want to add it. 

![image](https://user-images.githubusercontent.com/32607317/219976884-714fca98-0a1a-483e-8264-abeaec109ece.png)

I get that this is kind of a "too hot" or "too cold" nit-pick, but was wondering if a different lookback behavior would make sense. If I need to just stick with global, that's a fine response too.

**Comment by Renji-XD** [comment]
It is probably the quickest and easiest to change the type for the last line option to a configureable number instead of being a checkbox as compromise. Time based sounds like an overkill for most of the people (also not sure how that should/would work - on the "official" page by anacreon at least i can't see anything like that)
